import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Header from '@/components/Header/Header'
import AboutUs from '@/components/AboutUs/AboutUs'
import Articles from '@/components/Articles/Articles'
import Footer from '@/components/Footer/Footer'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>FoodTruck</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='relative'>
		<Navbar/>
        <Header/>
		<AboutUs/>
		<Articles/>
		<Footer/>
      </main>
    </>
  )
}
